-- Solution 1: (1096 ms, 0 B)

WITH RECURSIVE CTE AS
(
   SELECT DISTINCT '2019-01-01' AS DATE_RANGE, 1 AS N 
   UNION ALL
   SELECT DATE_RANGE + INTERVAL 1 DAY, N + 1 FROM CTE
   WHERE DATE_RANGE < '2019-12-31'
), SUCCESS AS
(
   SELECT 'succeeded' AS PERIOD_STATE, MIN(SUCCESS_DATE) AS START_DATE, MAX(SUCCESS_DATE) AS END_DATE
   FROM
   (
       SELECT SUCCESS_DATE, B.N - ROW_NUMBER() OVER (ORDER BY SUCCESS_DATE) AS GRP
       FROM SUCCEEDED A
       INNER JOIN CTE B
       ON A.SUCCESS_DATE = B.DATE_RANGE
   ) A
   GROUP BY GRP
), FAILURE AS
(
   SELECT 'failed' AS PERIOD_STATE, MIN(FAIL_DATE) AS START_DATE, MAX(FAIL_DATE) AS END_DATE
   FROM
   (
       SELECT FAIL_DATE, B.N - ROW_NUMBER() OVER (ORDER BY FAIL_DATE) AS GRP
       FROM FAILED A
       INNER JOIN CTE B
       ON A.FAIL_DATE = B.DATE_RANGE
   ) A
   GROUP BY GRP
)  

SELECT * FROM SUCCESS
UNION ALL
SELECT * FROM FAILURE
ORDER BY 2;
