-- Solution 1: (322 ms,	0 B)

WITH TEMP AS
(
    SELECT A.*, ROW_NUMBER() OVER(PARTITION BY USERNAME ORDER BY ENDDATE DESC) AS ROW_NUM, CNT
    FROM USERACTIVITY A
    LEFT JOIN
    (
       SELECT USERNAME, COUNT(*) AS CNT
       FROM USERACTIVITY
       GROUP BY 1
    ) B
    ON A.USERNAME = B.USERNAME
)

SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE FROM TEMP
WHERE CNT = 1
UNION
SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE FROM TEMP
WHERE CNT > 1 AND ROW_NUM = 2;