-- Solution 1: (493 ms,	0 B)

WITH RECURSIVE CTE AS
(
   SELECT MIN(PERIOD_START) AS DATE_RANGE FROM SALES
   UNION ALL
   SELECT DATE_RANGE + INTERVAL 1 DAY 
   FROM CTE
   WHERE DATE_RANGE < (SELECT MAX(PERIOD_END) FROM SALES)
)

SELECT A.product_id, C.product_name, CAST(YEAR(B.DATE_RANGE) AS CHAR) AS report_year, 
       COUNT(B.DATE_RANGE)*A.AVERAGE_DAILY_SALES AS total_amount
FROM SALES A
LEFT JOIN CTE B
ON B.DATE_RANGE >= A.PERIOD_START AND B.DATE_RANGE <= A.PERIOD_END
LEFT JOIN PRODUCT C
ON A.PRODUCT_ID = C.PRODUCT_ID
GROUP BY 1,2,3
ORDER BY 1,3;
