-- Solution 1: (463 ms,	0 B)

WITH MARKS AS
(
   SELECT EXAM_ID, MIN(SCORE) AS MIN_SCORE, MAX(SCORE) AS MAX_SCORE
   FROM EXAM
   GROUP BY 1
),
BOTTOM AS
(
   SELECT DISTINCT A.EXAM_ID, STUDENT_ID
   FROM EXAM A
   LEFT JOIN MARKS B
   ON A.EXAM_ID = B.EXAM_ID 
   WHERE A.SCORE = B.MIN_SCORE
),TOP AS
(
   SELECT A.EXAM_ID, STUDENT_ID
   FROM EXAM A
   LEFT JOIN MARKS B
   ON A.EXAM_ID = B.EXAM_ID 
   WHERE A.SCORE = B.MAX_SCORE
), ATTENDED AS
(
   SELECT DISTINCT STUDENT_ID FROM EXAM
)


SELECT A.* FROM STUDENT A
WHERE STUDENT_ID IN (SELECT DISTINCT STUDENT_ID FROM ATTENDED) AND
STUDENT_ID NOT IN 
(
    SELECT DISTINCT STUDENT_ID FROM TOP
    UNION
    SELECT DISTINCT STUDENT_ID FROM BOTTOM
);
