-- Solution 1: (562 ms,	0 B)

SELECT A.ITEM_CATEGORY AS CATEGORY, COALESCE(SUM(CASE WHEN WEEKDAY = 'Monday' THEN QUANTITY END),0) AS MONDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Tuesday' THEN QUANTITY END),0) AS TUESDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Wednesday' THEN QUANTITY END),0) AS WEDNESDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Thursday' THEN QUANTITY END),0) AS THURSDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Friday' THEN QUANTITY END),0) AS FRIDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Saturday' THEN QUANTITY END),0) AS SATURDAY,
                                  COALESCE(SUM(CASE WHEN WEEKDAY = 'Sunday' THEN QUANTITY END),0) AS SUNDAY
FROM ITEMS A
LEFT JOIN
(
    SELECT A.*, DATE_FORMAT(ORDER_DATE,'%W') AS WEEKDAY
    FROM ORDERS A
) B
ON A.ITEM_ID = B.ITEM_ID
GROUP BY 1
ORDER BY 1;