-- Solution 1: (578 ms,	0 B)

WITH RECURSIVE CTE AS
(
   SELECT TASK_ID, 1 AS N
   FROM TASKS
   UNION ALL
   SELECT TASK_ID, N + 1 AS N
   FROM CTE 
   WHERE N < (SELECT MAX(SUBTASKS_COUNT) FROM TASKS)
), CTE2 AS
(
   SELECT A.* 
   FROM CTE A
   INNER JOIN TASKS B
   ON A.TASK_ID = B.TASK_ID
   AND A.N <= B.SUBTASKS_COUNT
)

SELECT TASK_ID, N AS SUBTASK_ID 
FROM CTE2 A
WHERE CONCAT(TASK_ID,'-',N) NOT IN (SELECT CONCAT(TASK_ID,'-', SUBTASK_ID) AS COMB FROM EXECUTED);
