-- Solution 1: (450 ms,	0 B)

WITH SENIORS AS
(
    SELECT A.*, SUM(SALARY) OVER (ORDER BY SALARY ASC) AS CUM_SUM
    FROM CANDIDATES A
    WHERE EXPERIENCE = 'Senior'
), JUNIORS AS
(
    SELECT A.*, CUM_SUM + SEN_CUM_SUM AS FINAL_CUM_SUM 
    FROM 
    (
        SELECT A.*, SUM(SALARY) OVER (ORDER BY SALARY ASC) AS CUM_SUM, SEN_CUM_SUM
        FROM CANDIDATES A
        CROSS JOIN 
        (SELECT CASE WHEN MAX(CUM_SUM) IS NULL THEN 0 ELSE MAX(CUM_SUM) END AS SEN_CUM_SUM FROM SENIORS WHERE CUM_SUM < 70000) B
        WHERE EXPERIENCE = 'Junior'
    ) A
    HAVING FINAL_CUM_SUM < 70000
)

SELECT DISTINCT EMPLOYEE_ID FROM SENIORS
WHERE CUM_SUM < 70000
UNION
SELECT DISTINCT EMPLOYEE_ID FROM JUNIORS;