-- Solution 1: (573 ms, 0 B)

WITH BANNED_CLIENTS AS
(
   SELECT DISTINCT USERS_ID FROM USERS
   WHERE ROLE = 'client' AND BANNED = 'Yes'
),
BANNED_DRIVERS AS
(
   SELECT DISTINCT USERS_ID FROM USERS
   WHERE ROLE = 'driver' AND BANNED = 'Yes'
)


SELECT REQUEST_AT AS Day, ROUND((CANCELED_TRIPS/TOTAL_TRIPS),2) AS "Cancellation Rate"
FROM
(
        SELECT REQUEST_AT, COUNT(DISTINCT CASE WHEN STATUS LIKE '%CANCEL%' THEN ID END) AS CANCELED_TRIPS,
                   COUNT(DISTINCT ID) AS TOTAL_TRIPS
        FROM
        (
            SELECT * FROM TRIPS
            WHERE CLIENT_ID NOT IN (SELECT * FROM BANNED_CLIENTS)
            AND DRIVER_ID NOT IN (SELECT * FROM BANNED_DRIVERS)
        ) A    
        WHERE REQUEST_AT >= '2013-10-01' AND REQUEST_AT <= '2013-10-03'
        GROUP BY 1
) A;