-- Solution 1: (406 ms,	0 B)

WITH MEDIAN_RANGE AS
(
   SELECT COMPANY, FLOOR((MAXX+MINN)/2) AS LOWER,
                   CEIL((MAXX+MINN)/2) AS UPPER
   FROM
   ( 
       SELECT COMPANY, MAX(ROW_NUM) AS MAXX, MIN(ROW_NUM) AS MINN
       FROM
       ( 
           SELECT ID, COMPANY, SALARY, ROW_NUMBER () OVER (PARTITION BY COMPANY ORDER BY SALARY) AS ROW_NUM
           FROM EMPLOYEE
       ) A
       GROUP BY 1
   ) A 
)

SELECT DISTINCT A.ID, A.COMPANY, A.SALARY FROM
(
    SELECT ID, COMPANY, SALARY, ROW_NUMBER () OVER (PARTITION BY COMPANY ORDER BY SALARY) AS ROW_NUM
    FROM EMPLOYEE
) A
LEFT JOIN MEDIAN_RANGE B
ON A.COMPANY = B.COMPANY
WHERE A.ROW_NUM >= B.LOWER AND A.ROW_NUM <= B.UPPER;
