-- Solution 1: (283 ms,	0 B)

WITH CTE AS
(
   SELECT A.*, ID - R_NUM AS DIFF
   FROM
   (
       SELECT A.*, ROW_NUMBER() OVER (ORDER BY ID) AS R_NUM
       FROM
       (
           SELECT A.*, CASE WHEN PEOPLE >= 100 THEN 1 ELSE 0 END AS FLAG
           FROM STADIUM A
       ) A
       WHERE FLAG = 1
   ) A
), CTE2 AS
(
    SELECT DIFF, COUNT(*) AS CNT
    FROM CTE
    GROUP BY 1
    HAVING CNT >= 3
)

SELECT ID, VISIT_DATE, PEOPLE 
FROM CTE A
WHERE DIFF IN (SELECT DISTINCT DIFF FROM CTE2)
ORDER BY 2;