-- Solution 1: (427 ms, 0 B)

WITH DIST_PRODUCTS AS
(
   SELECT COUNT(DISTINCT PRODUCT_KEY) AS DIST
   FROM PRODUCT
)

SELECT CUSTOMER_ID
FROM CUSTOMER 
GROUP BY 1
HAVING COUNT(DISTINCT PRODUCT_KEY) = (SELECT DIST FROM DIST_PRODUCTS);