-- Solution 1: (1177 ms, 0 B)

WITH FIRST_YEAR AS 
(
   SELECT PRODUCT_ID, MIN(YEAR) AS FIRST_YEAR
   FROM SALES
   GROUP BY 1 
)

SELECT A.PRODUCT_ID, YEAR AS FIRST_YEAR, QUANTITY, PRICE
FROM SALES A
LEFT JOIN FIRST_YEAR B
ON A.PRODUCT_ID = B.PRODUCT_ID 
WHERE A.YEAR = B.FIRST_YEAR;