-- Solution 1: (704 ms, 0 B)

SELECT DISTINCT PROJECT_ID, EMPLOYEE_ID
FROM
(
    SELECT A.*, B.EXPERIENCE_YEARS, DENSE_RANK() OVER (PARTITION BY PROJECT_ID ORDER BY EXPERIENCE_YEARS DESC) AS ROW_NUM
    FROM PROJECT A
    LEFT JOIN EMPLOYEE B
    ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
) A
WHERE ROW_NUM = 1;