-- Solution 1: (985 ms, 0 B)

WITH QUANTITY AS
(
   SELECT BOOK_ID, SUM(QUANTITY) AS QUANT
   FROM ORDERS
   WHERE DISPATCH_DATE > DATE_ADD('2019-06-23', INTERVAL -1 YEAR) AND DISPATCH_DATE < '2019-06-23'
   GROUP BY 1    
)

SELECT BOOK_ID, NAME
FROM
(
    SELECT A.*, CASE WHEN B.QUANT IS NULL THEN 0 ELSE B.QUANT END AS QUANT
    FROM BOOKS A
    LEFT JOIN QUANTITY B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE AVAILABLE_FROM < DATE_ADD('2019-06-23', INTERVAL -1 MONTH)
) A  
WHERE QUANT < 10;
