-- Solution 1: (485 ms, 0 B)

SELECT LOGIN_DATE, COUNT(USER_ID) AS USER_COUNT
FROM
(
    SELECT USER_ID, MIN(ACTIVITY_DATE) AS LOGIN_DATE
    FROM TRAFFIC
    WHERE ACTIVITY = 'login' 
    GROUP BY 1
) A   
WHERE LOGIN_DATE >= DATE_ADD('2019-06-30', INTERVAL -90 DAY) AND LOGIN_DATE <= '2019-06-30'
GROUP BY 1;