-- Solution 1: (923 ms,	0 B)

WITH AVG_ACT AS
(
   SELECT EVENT_TYPE, AVG(OCCURENCES) AS AVR
   FROM EVENTS
   GROUP BY 1
)

SELECT BUSINESS_ID FROM
(
    SELECT BUSINESS_ID, SUM(FLAG) AS FLAG
    FROM
    (
        SELECT A.*, B.AVR, CASE WHEN OCCURENCES > AVR THEN 1 ELSE 0 END AS FLAG
        FROM EVENTS A
        LEFT JOIN AVG_ACT B
        ON A.EVENT_TYPE = B.EVENT_TYPE
    ) A 
    GROUP BY 1
) A    
WHERE FLAG > 1;