-- Solution 1: (778 ms, 0 B)

WITH SPAM_TOTAL AS
(
   SELECT ACTION_DATE, COUNT(DISTINCT POST_ID) AS TOT_POSTS 
   FROM ACTIONS A
   WHERE EXTRA = 'spam' AND ACTION = 'report'
   GROUP BY 1
),
SPAM_REMOVED AS
(
   SELECT ACTION_DATE, COUNT(DISTINCT POST_ID) AS REM_POSTS 
   FROM ACTIONS A
   WHERE EXTRA = 'spam' AND ACTION = 'report'
   AND POST_ID IN (SELECT DISTINCT POST_ID FROM REMOVALS) 
   GROUP BY 1
)

SELECT ROUND(AVG(REM_POSTS*100/TOT_POSTS),2) AS AVERAGE_DAILY_PERCENT
FROM
(
    SELECT A.ACTION_DATE, CASE WHEN REM_POSTS IS NULL THEN 0 ELSE REM_POSTS END AS REM_POSTS, TOT_POSTS
    FROM SPAM_TOTAL A
    LEFT JOIN SPAM_REMOVED B
    ON A.ACTION_DATE = B.ACTION_DATE
) A;