-- Solution 1: (420 ms, 0 B)

SELECT DISTINCT VIEWER_ID AS ID 
FROM
(
    SELECT VIEWER_ID, VIEW_DATE, COUNT(DISTINCT ARTICLE_ID) AS CNT
    FROM VIEWS
    GROUP BY 1,2
    HAVING CNT > 1
) A;