-- Solution 1: (1238 ms, 0 B)

WITH ORDERS1 AS
(
   SELECT BUYER_ID, COUNT(DISTINCT ORDER_ID) AS ORDERS
   FROM ORDERS
   WHERE ORDER_DATE >= '2019-01-01' AND ORDER_DATE <= '2019-12-31'
   GROUP BY 1
)

SELECT DISTINCT USER_ID AS BUYER_ID, JOIN_DATE, CASE WHEN ORDERS IS NULL THEN 0 ELSE ORDERS END AS ORDERS_IN_2019
FROM USERS A
LEFT JOIN ORDERS1 B
ON A.USER_ID = B.BUYER_ID;