-- Solution 1: (411 ms, 0 B)

WITH PROD AS 
(
    SELECT * FROM
    (
        SELECT A.*, ROW_NUMBER () OVER (PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC) AS R_N
        FROM PRODUCTS A
        WHERE CHANGE_DATE <= '2019-08-16'
    ) A
    WHERE R_N = 1
)    

SELECT DISTINCT A.PRODUCT_ID, CASE WHEN B.PRODUCT_ID IS NULL THEN 10 ELSE B.NEW_PRICE END AS PRICE
FROM PRODUCTS A
LEFT JOIN PROD B
ON A.PRODUCT_ID = B.PRODUCT_ID;