-- Solution 1: (536 ms, 0 B)

SELECT ROUND(IMM*100/TOT,2) AS IMMEDIATE_PERCENTAGE
FROM
(
    SELECT SUM(FLAG) AS IMM, COUNT(DISTINCT DELIVERY_ID) AS TOT FROM
    (
        SELECT A.*, CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END AS FLAG,
        ROW_NUMBER () OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS R_N
        FROM DELIVERY A
    ) A
    WHERE R_N = 1
) A;