-- Solution 1: (492 ms, 0 B)

SELECT MONTH, COUNTRY, CASE WHEN TRANS_COUNT IS NULL THEN 0 ELSE TRANS_COUNT END AS TRANS_COUNT,
                       CASE WHEN APPROVED_COUNT IS NULL THEN 0 ELSE APPROVED_COUNT END AS APPROVED_COUNT,
                       CASE WHEN TRANS_TOTAL_AMOUNT IS NULL THEN 0 ELSE TRANS_TOTAL_AMOUNT END AS TRANS_TOTAL_AMOUNT,
                       CASE WHEN APPROVED_TOTAL_AMOUNT IS NULL THEN 0 ELSE APPROVED_TOTAL_AMOUNT END AS APPROVED_TOTAL_AMOUNT
FROM
(
    SELECT MONTH, COUNTRY, COUNT(DISTINCT ID) AS TRANS_COUNT,
                           COUNT(DISTINCT CASE WHEN STATE = 'approved' THEN ID END) AS APPROVED_COUNT,
                           SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
                           SUM(CASE WHEN STATE = 'approved' THEN AMOUNT END) AS APPROVED_TOTAL_AMOUNT
    FROM
    ( 
        SELECT A.*, DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH
        FROM TRANSACTIONS A
    ) A
    GROUP BY 1,2
) A;    