-- Solution 1: (812 ms, 0 B)

SELECT PERSON_NAME
FROM
(
    SELECT TURN, PERSON_NAME
    FROM
    (
        SELECT A.*, SUM(WEIGHT) OVER (ORDER BY TURN) AS WEIGHT_SUM
        FROM QUEUE A
        ORDER BY TURN
    ) A   
    WHERE WEIGHT_SUM <= 1000
    ORDER BY TURN DESC
) A
LIMIT 1;