-- Solution 1: (613 ms, 0 B)

WITH POINTS AS 
(
    SELECT A.*, CASE WHEN HOST_GOALS > GUEST_GOALS THEN 3 
                     WHEN HOST_GOALS = GUEST_GOALS THEN 1
                     WHEN HOST_GOALS < GUEST_GOALS THEN 0 END AS HOST_PTS,
                CASE WHEN HOST_GOALS < GUEST_GOALS THEN 3 
                     WHEN HOST_GOALS = GUEST_GOALS THEN 1
                     WHEN HOST_GOALS > GUEST_GOALS THEN 0 END AS GUEST_PTS
    FROM MATCHES A
)    

SELECT TEAM_ID, TEAM_NAME, CASE WHEN NUM_POINTS IS NULL THEN 0 ELSE NUM_POINTS END AS NUM_POINTS
FROM
(
    SELECT TEAM_ID, TEAM_NAME, SUM(HOST_PTS) AS NUM_POINTS
    FROM TEAMS A
    LEFT JOIN 
    (
        SELECT HOST_TEAM, SUM(HOST_PTS) AS HOST_PTS
        FROM POINTS
        GROUP BY 1
        UNION ALL
        SELECT GUEST_TEAM, SUM(GUEST_PTS) AS GUEST_PTS
        FROM POINTS
        GROUP BY 1
    ) B
    ON A.TEAM_ID = B.HOST_TEAM
    GROUP BY 1,2
    ORDER BY 3 DESC, TEAM_ID
) A   
 ORDER BY 3 DESC, TEAM_ID;