-- Solution 1: (599 ms, 0 B)

WITH FRIENDS AS
(
   SELECT DISTINCT USER1_ID FROM FRIENDSHIP
   WHERE USER2_ID = 1
   UNION
   SELECT DISTINCT USER2_ID FROM FRIENDSHIP
   WHERE USER1_ID = 1 
)

SELECT DISTINCT PAGE_ID AS RECOMMENDED_PAGE
FROM
(
    SELECT * FROM LIKES
    WHERE USER_ID IN (SELECT * FROM FRIENDS)
) A  
WHERE PAGE_ID NOT IN (SELECT DISTINCT PAGE_ID FROM LIKES WHERE USER_ID = 1);