-- Solution 1: (221 ms,	0 B)

WITH LVL1 AS 
(
   SELECT DISTINCT EMPLOYEE_ID
   FROM EMPLOYEES
   WHERE MANAGER_ID = 1
),
LVL2 AS
(
   SELECT DISTINCT EMPLOYEE_ID
   FROM EMPLOYEES
   WHERE MANAGER_ID IN (SELECT * FROM LVL1)
),
LVL3 AS
(
   SELECT DISTINCT EMPLOYEE_ID
   FROM EMPLOYEES
   WHERE MANAGER_ID IN (SELECT * FROM LVL2)
)

SELECT * FROM LVL3
WHERE EMPLOYEE_ID != 1;