-- Solution 1: (298 ms,	0 B)

WITH FILTERED_DATES AS
(
   SELECT DISTINCT VISITED_ON
   FROM CUSTOMER
   WHERE VISITED_ON >= (SELECT MIN(VISITED_ON) + 6 FROM CUSTOMER)
), UPDATED_AMOUNTS AS
(
   SELECT VISITED_ON, SUM(AMOUNT) AS FINAL_AMT
   FROM CUSTOMER
   GROUP BY 1
)

SELECT VISITED_ON, AMOUNT, ROUND((AMOUNT/7),2) AS AVERAGE_AMOUNT
FROM
(
    SELECT VISITED_ON, SUM(FINAL_AMT) OVER (ORDER BY VISITED_ON DESC ROWS BETWEEN CURRENT ROW AND 6 FOLLOWING) AS AMOUNT
    FROM UPDATED_AMOUNTS
) A
WHERE VISITED_ON IN (SELECT * FROM FILTERED_DATES)
ORDER BY 1;
