-- Solution 1: (1071 ms, 0 B)

WITH TEMP1 AS 
(
  SELECT DISTINCT NAME 
  FROM
  (  
      SELECT USER_ID, MOVIES, NAME, ROW_NUMBER() OVER(ORDER BY MOVIES DESC, NAME) AS ROW_NUM
      FROM
      (
          SELECT A.USER_ID, NAME, COUNT(DISTINCT MOVIE_ID) AS MOVIES
          FROM MOVIERATING A
          LEFT JOIN USERS B
          ON A.USER_ID = B.USER_ID
          GROUP BY 1,2
      ) A   
  ) A    
  WHERE ROW_NUM = 1
),
TEMP2 AS 
(
  SELECT DISTINCT TITLE 
  FROM
  (  
      SELECT MOVIE_ID, TITLE, RATING, ROW_NUMBER() OVER(ORDER BY RATING DESC, TITLE) AS ROW_NUM
      FROM
      (
          SELECT A.MOVIE_ID, TITLE, AVG(RATING) AS RATING
          FROM MOVIERATING A
          LEFT JOIN MOVIES B
          ON A.MOVIE_ID = B.MOVIE_ID
          WHERE CREATED_AT >= '2020-02-01' AND CREATED_AT <= '2020-02-29'
          GROUP BY 1,2
      ) A   
  ) A    
  WHERE ROW_NUM = 1
)

SELECT NAME AS RESULTS FROM TEMP1
UNION 
SELECT * FROM TEMP2;