-- Solution 1: (542 ms, 0 B)

WITH MAXX AS
(
      SELECT ACTIVITY, COUNT(DISTINCT ID) AS FRIENDS
      FROM FRIENDS
      GROUP BY 1
      ORDER BY 2 DESC
      LIMIT 1 
),
MINN AS
(
      SELECT ACTIVITY, COUNT(DISTINCT ID) AS FRIENDS
      FROM FRIENDS
      GROUP BY 1
      ORDER BY 2 ASC
      LIMIT 1  
)

SELECT DISTINCT ACTIVITY 
FROM 
(
   SELECT ACTIVITY, COUNT(DISTINCT ID) AS FRIENDS
   FROM FRIENDS
   GROUP BY 1 
) A  
WHERE FRIENDS != (SELECT DISTINCT FRIENDS FROM MAXX) AND FRIENDS != (SELECT DISTINCT FRIENDS FROM MINN);
