-- Solution 1: (1600 ms, 0 B)

SELECT INVOICE_ID, B.CUSTOMER_NAME, PRICE, COUNT(DISTINCT CONTACT_NAME) AS CONTACTS_CNT,
       COUNT(DISTINCT CASE WHEN FLAG = 1 THEN CONTACT_NAME END) AS TRUSTED_CONTACTS_CNT                
FROM INVOICES A
LEFT JOIN CUSTOMERS B
ON A.USER_ID = B.CUSTOMER_ID
LEFT JOIN 
(
    SELECT A.*, CASE WHEN B.CUSTOMER_NAME IS NOT NULL THEN 1 ELSE 0 END AS FLAG
    FROM CONTACTS A
    LEFT JOIN CUSTOMERS B
    ON A.CONTACT_EMAIL = B.EMAIL
) C    
ON A.USER_ID = C.USER_ID
GROUP BY 1,2,3
ORDER BY 1;