-- Solution 1: (800 ms, 0 B)

SELECT STOCK_NAME, SUM(CAPITAL_GAIN_LOSS) AS CAPITAL_GAIN_LOSS
FROM
(
    SELECT A.*, PRICE - PREVIOUS_PRICE AS CAPITAL_GAIN_LOSS
    FROM 
    (
        SELECT A.*, LAG(PRICE) OVER (PARTITION BY STOCK_NAME ORDER BY R_N) AS PREVIOUS_PRICE
        FROM
        (
            SELECT A.*, ROW_NUMBER() OVER(PARTITION BY STOCK_NAME ORDER BY OPERATION_DAY) AS R_N
            FROM STOCKS A
            ORDER BY STOCK_NAME, R_N
        ) A
    ) A
    WHERE OPERATION = 'Sell'
) A
GROUP BY 1;