-- Solution 1: (685 ms, 0 B)

WITH TEMP_A AS 
(
    SELECT DISTINCT A.CUSTOMER_ID, B.CUSTOMER_NAME 
    FROM ORDERS A
    LEFT JOIN CUSTOMERS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
    WHERE PRODUCT_NAME = 'A' 
), TEMP_B AS 
(
    SELECT DISTINCT A.CUSTOMER_ID, B.CUSTOMER_NAME 
    FROM ORDERS A
    LEFT JOIN CUSTOMERS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
    WHERE PRODUCT_NAME = 'B' 
), TEMP_C AS 
(
    SELECT DISTINCT A.CUSTOMER_ID, B.CUSTOMER_NAME 
    FROM ORDERS A
    LEFT JOIN CUSTOMERS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
    WHERE PRODUCT_NAME = 'C' 
)


SELECT A.* FROM TEMP_A A 
INNER JOIN TEMP_B B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
WHERE A.CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM TEMP_C);
