-- Solution 1: (379 ms, 0 B)

SELECT SALE_DATE, APPLES - ORANGES AS DIFF
FROM
(
    SELECT SALE_DATE, MAX(APPLES) AS APPLES, MAX(ORANGES) AS ORANGES
    FROM
    (
        SELECT SALE_DATE, CASE WHEN FRUIT = 'apples' THEN SOLD_NUM END AS APPLES,
                          CASE WHEN FRUIT = 'oranges' THEN SOLD_NUM END AS ORANGES
        FROM SALES
    ) A
    GROUP BY 1
) A
ORDER BY 1;