-- Solution 1: (1428 ms, 0 B)

WITH RECURSIVE CTE AS
(
   SELECT ID, MIN(LOGIN_DATE) AS DATE_RANGE, 1 AS N
   FROM LOGINS
   GROUP BY 1
   UNION ALL
   SELECT A.ID, DATE_RANGE + INTERVAL 1 DAY, N+1
   FROM CTE A
   WHERE DATE_RANGE < (SELECT MAX(LOGIN_DATE) FROM LOGINS)
)

SELECT DISTINCT A.ID, B.NAME
FROM
(
    SELECT ID, GRP, COUNT(DISTINCT LOGIN_DATE) AS CONS_DAYS
    FROM
    (
        SELECT A.*, B.N - DENSE_RANK() OVER (PARTITION BY A.ID ORDER BY LOGIN_DATE) AS GRP
        FROM LOGINS A
        INNER JOIN CTE B
        ON A.ID = B.ID AND A.LOGIN_DATE = B.DATE_RANGE
    ) A
    GROUP BY 1,2
) A
LEFT JOIN ACCOUNTS B
ON A.ID = B.ID
WHERE CONS_DAYS >= 5
ORDER BY 1;
