-- Solution 1: (641 ms,	0 B)

WITH TAX_SLAB AS
(
   SELECT A.*, CASE WHEN MAX_SALARY < 1000 THEN 0
                    WHEN MAX_SALARY >= 1000 AND MAX_SALARY <= 10000 THEN 24
                    WHEN MAX_SALARY > 10000 THEN 49 END AS TAX_SLAB
   FROM
   (
       SELECT COMPANY_ID, MAX(SALARY) AS MAX_SALARY
       FROM SALARIES
       GROUP BY 1
   ) A
    ORDER BY 1
)

SELECT A.COMPANY_ID, A.EMPLOYEE_ID, A.EMPLOYEE_NAME, ROUND(SALARY - (TAX_SLAB*SALARY/100)) AS SALARY
FROM SALARIES A
LEFT JOIN TAX_SLAB B
ON A.COMPANY_ID = B.COMPANY_ID;