-- Solution 1: (1168 ms, 0 B)

WITH TEMP AS
(
    SELECT A.*, B.NAME AS COUNTRY
    FROM 
    (
       SELECT A.*, LEFT(PHONE_NUMBER, 3) AS LEF
       FROM PERSON A
    ) A    
    LEFT JOIN COUNTRY B
    ON A.LEF = B.COUNTRY_CODE
),TEMP1 AS
(
    SELECT A.*, B.COUNTRY AS COUNTRY1, C.COUNTRY AS COUNTRY2
    FROM CALLS A
    LEFT JOIN TEMP B
    ON A.CALLER_ID = B.ID
    LEFT JOIN TEMP C
    ON A.CALLEE_ID = C.ID
), TEMP2 AS
(
    SELECT SUM(DURATION)/COUNT(CALLER_ID) AS GLOBAL_AVG
    FROM CALLS
)

SELECT DISTINCT COUNTRY1 AS COUNTRY
FROM
(
    SELECT COUNTRY1, DURATION1/NO_CALLS AS AVRG, GLOBAL_AVG 
    FROM
    (
        SELECT COUNTRY1, SUM(DURATION1) AS DURATION1, SUM(NO_CALLS) AS NO_CALLS
        FROM
        (
            SELECT COUNTRY1, SUM(DURATION) AS DURATION1, COUNT(CALLER_ID) AS NO_CALLS
            FROM TEMP1
            GROUP BY 1
            UNION ALL
            SELECT COUNTRY2, SUM(DURATION) AS DURATION2, COUNT(CALLER_ID) AS NO_CALLS
            FROM TEMP1
            GROUP BY 1
        ) A
        GROUP BY 1
    ) A
    CROSS JOIN TEMP2
) A
WHERE AVRG > GLOBAL_AVG;