-- Solution 1: (1017 ms, 0 B)

SELECT NAME AS CUSTOMER_NAME, CUSTOMER_ID, ORDER_ID, ORDER_DATE
FROM
(
    SELECT A.*, NAME, ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS ROW_NUM
    FROM ORDERS A
    LEFT JOIN CUSTOMERS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
) A
WHERE ROW_NUM <= 3
ORDER BY 1,2,4 DESC;
