-- Solution 1: (1539 ms, 0 B)

SELECT A.PRODUCT_NAME, A.PRODUCT_ID, B.ORDER_ID, B.ORDER_DATE
FROM PRODUCTS A
INNER JOIN 
( 
    SELECT * FROM
    (
        SELECT A.PRODUCT_ID, A.ORDER_DATE, A.ORDER_ID, RANK() OVER(PARTITION BY PRODUCT_ID ORDER BY ORDER_DATE DESC) AS R_N
        FROM ORDERS A
    ) A
    WHERE R_N = 1
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 1,2,3;