-- Solution 1: (2001 ms, 0 B)

SELECT CUSTOMER_ID, A.PRODUCT_ID, PRODUCT_NAME 
FROM
(
    SELECT A.*, RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY NO_ORDERS DESC) AS R_NUM
    FROM
    (
        SELECT CUSTOMER_ID, PRODUCT_ID, COUNT(DISTINCT ORDER_ID) AS NO_ORDERS
        FROM ORDERS
        GROUP BY 1,2
    ) A
) A  
LEFT JOIN PRODUCTS B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE R_NUM = 1;