-- Solution 1: (427 ms,	0 B)

WITH RECURSIVE TEMP AS
(
   SELECT 1 AS N
   UNION ALL
   SELECT N + 1 FROM TEMP
   WHERE N < (SELECT MAX(CUSTOMER_ID) FROM CUSTOMERS)
)

SELECT DISTINCT N AS IDS
FROM TEMP 
WHERE N NOT IN (SELECT DISTINCT CUSTOMER_ID FROM CUSTOMERS)
ORDER BY 1;