-- Solution 1: (579 ms, 0 B)

SELECT CASE WHEN FROM_ID > TO_ID THEN TO_ID ELSE FROM_ID END AS PERSON1,
       CASE WHEN FROM_ID < TO_ID THEN TO_ID ELSE FROM_ID END AS PERSON2,
       COUNT(*) AS CALL_COUNT, SUM(DURATION) AS TOTAL_DURATION
FROM CALLS A
GROUP BY 1,2;

-- Solution 2: (1450 ms, 0 B)
WITH TEMP1 AS
(
    SELECT FROM_ID AS PERSON1, TO_ID AS PERSON2, COUNT(*) AS CALL_COUNT, SUM(DURATION) AS TOTAL_DURATION
    FROM CALLS A
    WHERE FROM_ID < TO_ID
    GROUP BY 1,2
), TEMP2 AS
(
    SELECT FROM_ID AS PERSON1, TO_ID AS PERSON2, COUNT(*) AS CALL_COUNT, SUM(DURATION) AS TOTAL_DURATION
    FROM CALLS A
    WHERE FROM_ID > TO_ID
    GROUP BY 1,2
)

SELECT PERSON1, PERSON2, SUM(CALL_COUNT) AS CALL_COUNT, SUM(TOTAL_DURATION) AS TOTAL_DURATION
FROM
(
    SELECT * FROM TEMP1
    UNION ALL
    SELECT PERSON2, PERSON1, CALL_COUNT, TOTAL_DURATION FROM TEMP2
) A
GROUP BY 1,2;