-- Solution 1: (540 ms,	0 B)

WITH TEMP AS
(  
   SELECT USER_ID, VISIT_DATE
   FROM USERVISITS
   UNION
   SELECT DISTINCT USER_ID, CAST('2021-01-01' AS DATE) AS VISIT_DATE
   FROM USERVISITS
   ORDER BY 1,2
)


SELECT USER_ID, MAX(DIFF) AS BIGGEST_WINDOW
FROM
(
    SELECT USER_ID, ABS(DATEDIFF(VISIT_DATE, LEAD(VISIT_DATE) OVER (PARTITION BY USER_ID ORDER BY VISIT_DATE))) AS DIFF
    FROM TEMP
) A
GROUP BY 1
ORDER BY 1;