-- Solution 1: (214 ms,	0 B)

SELECT COALESCE
(
(
    SELECT DISTINCT SALARY
    FROM
    (
        SELECT ID, SALARY, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS ROW_NUM
        FROM EMPLOYEE
    ) A
    WHERE ROW_NUM = 2
), NULL) AS SECONDHIGHESTSALARY ;
    