-- Solution 1: (1397 ms, 0 B)
 
WITH WIMB AS
(
   SELECT WIMBLEDON, COUNT(*) AS CNT
   FROM CHAMPIONSHIPS
   GROUP BY 1
), FR_OPEN AS
(
   SELECT FR_OPEN, COUNT(*) AS CNT
   FROM CHAMPIONSHIPS
   GROUP BY 1
), US_OPEN AS
(
   SELECT US_OPEN, COUNT(*) AS CNT
   FROM CHAMPIONSHIPS
   GROUP BY 1
), AU_OPEN AS
(
   SELECT AU_OPEN, COUNT(*) AS CNT
   FROM CHAMPIONSHIPS
   GROUP BY 1
)

SELECT PLAYER_ID, PLAYER_NAME, WIMB+FR+US+AU AS GRAND_SLAMS_COUNT
FROM
(
    SELECT A.*, COALESCE(B.CNT,0) AS WIMB, COALESCE(C.CNT,0) AS FR, COALESCE(D.CNT,0) AS US, COALESCE(E.CNT,0) AS AU
    FROM PLAYERS A
    LEFT JOIN WIMB B
    ON A.PLAYER_ID = B.WIMBLEDON
    LEFT JOIN FR_OPEN C
    ON A.PLAYER_ID = C.FR_OPEN
    LEFT JOIN US_OPEN D
    ON A.PLAYER_ID = D.US_OPEN
    LEFT JOIN AU_OPEN E
    ON A.PLAYER_ID = E.AU_OPEN
) A
HAVING GRAND_SLAMS_COUNT > 0;

