-- Solution 1: (481 ms,	0 B)


SELECT DISTINCT A.NUM AS CONSECUTIVENUMS
FROM LOGS A
INNER JOIN LOGS B
ON A.ID = B.ID + 1 AND A.NUM = B.NUM
INNER JOIN LOGS C
ON A.ID = C.ID - 1 AND A.NUM = C.NUM;

-- Solution 2: (443 ms,	0 B)

SELECT DISTINCT NUM AS CONSECUTIVENUMS
FROM
(
    SELECT NUM, LEAD(NUM) OVER(ORDER BY ID) AS NEXT_NUM,
                LAG(NUM) OVER(ORDER BY ID) AS PREV_NUM
    FROM LOGS
) A
WHERE NUM = PREV_NUM AND NUM = NEXT_NUM;