-- Solution 1: (650 ms,	0 B)

SELECT DISTINCT TRANSACTION_ID 
FROM
(
    SELECT A.*, DENSE_RANK() OVER (PARTITION BY FINAL_DAY ORDER BY AMOUNT DESC) AS RANKK
    FROM
    (
        SELECT A.*, DATE(DAY) AS FINAL_DAY
        FROM TRANSACTIONS A
    ) A     
) A
WHERE RANKK = 1
ORDER BY 1;
