-- Solution 1: (651 ms, 0 B)

WITH TEMP AS
(
    SELECT MAX(AVGG)
    FROM
    (
        SELECT ORDER_ID, QUANT/CNT AS AVGG
        FROM
        (
            SELECT ORDER_ID, COUNT(PRODUCT_ID) AS CNT, SUM(QUANTITY) AS QUANT
            FROM ORDERSDETAILS
            GROUP BY 1
        ) A 
    ) A
)    

SELECT DISTINCT ORDER_ID
FROM
(
    SELECT ORDER_ID, MAX(QUANTITY) AS MAXX
    FROM ORDERSDETAILS
    GROUP BY 1
) A
WHERE MAXX > (SELECT * FROM TEMP);