-- Solution 1: (503 ms,	0 B)

WITH TEMP AS
(
    SELECT USER_ID, USER, COUNT(*) AS CNT
    FROM
    (
        SELECT A.*, B.USER_ID AS USER
        FROM RELATIONS A
        LEFT JOIN RELATIONS B
        ON A.FOLLOWER_ID = B.FOLLOWER_ID
        WHERE A.USER_ID != B.USER_ID AND A.USER_ID < B.USER_ID
        ORDER BY 1
    ) A
    GROUP BY 1,2
    ORDER BY 3 DESC
)

SELECT USER_ID AS USER1_ID, USER AS USER2_ID
FROM TEMP
WHERE CNT =  (SELECT MAX(CNT) FROM TEMP);