-- Solution 1: (636 ms, 0 B)

SELECT DISTINCT SCHOOL_ID, SCORE
FROM
(
    SELECT A.*, ROW_NUMBER() OVER (PARTITION BY SCHOOL_ID ORDER BY SCORE ASC) AS ROW_NUM
    FROM
    (
        SELECT A.*, CASE WHEN B.SCORE IS NOT NULL THEN B.SCORE ELSE -1 END AS SCORE
        FROM SCHOOLS A
        LEFT JOIN EXAM B
        ON B.STUDENT_COUNT <= A.CAPACITY
    ) A
) A
WHERE ROW_NUM = 1
ORDER BY 1;