-- Solution 1: (672 ms, 0 B)

WITH TOT_PLAYERS AS
(
    SELECT COUNT(DISTINCT PLAYER_ID) AS TOT_PLAYERS
    FROM ACTIVITY
), 
MIN_DATE AS
(
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_DATE
    FROM ACTIVITY
    GROUP BY 1
)

SELECT ROUND((COUNT(A.PLAYER_ID)/TOT_PLAYERS),2) AS FRACTION
FROM
(
    SELECT DISTINCT A.PLAYER_ID
    FROM MIN_DATE A
    LEFT JOIN ACTIVITY B
    ON A.PLAYER_ID = B.PLAYER_ID
    WHERE DATEDIFF(B.EVENT_DATE,A.FIRST_DATE) = 1
) A  
CROSS JOIN TOT_PLAYERS B;