-- Solution 1: (293 ms, 0 B)

WITH NO_REPORTS AS
(
  SELECT MANAGERID, COUNT(DISTINCT ID) AS NO_REPORTS
  FROM EMPLOYEE
  GROUP BY 1
    HAVING NO_REPORTS > 4
)

SELECT DISTINCT NAME FROM EMPLOYEE
WHERE ID IN (SELECT DISTINCT MANAGERID FROM NO_REPORTS);