-- Solution 1: (342 ms, 0 B)

WITH VOTES AS
(
   SELECT CANDIDATEID, COUNT(DISTINCT ID) AS VOTES
   FROM VOTE
   GROUP BY 1
) 

SELECT NAME
FROM
(
    SELECT ID, NAME, VOTES
    FROM CANDIDATE A
    LEFT JOIN VOTES B
    ON A.ID = B.CANDIDATEID
    ORDER BY 3 DESC
) A
LIMIT 1;
