-- Solution 1: (783 ms, 0 B)

SELECT DEPT_NAME, COUNT(DISTINCT STUDENT_ID) AS STUDENT_NUMBER
FROM
(
    SELECT A.*, B.STUDENT_ID
    FROM DEPARTMENT A
    LEFT JOIN STUDENT B
    ON A.DEPT_ID = B.DEPT_ID
) A
GROUP BY 1
ORDER BY 2 DESC, 1;

