-- Solution 1: (277 ms, 0 B)

WITH SENT AS
(
   SELECT REQUESTER_ID, COUNT(*) AS CNT1
   FROM REQUESTACCEPTED
   GROUP BY 1
),
ACCEPTED AS
(
   SELECT ACCEPTER_ID, COUNT(*) AS CNT2
   FROM REQUESTACCEPTED
   GROUP BY 1
)

SELECT * FROM
(
    SELECT REQUESTER_ID AS ID, SUM(CNT1) AS NUM
    FROM
    (
        SELECT REQUESTER_ID, CNT1 FROM SENT
        UNION ALL
        SELECT ACCEPTER_ID, CNT2 FROM ACCEPTED
    ) A  
    GROUP BY 1
    ORDER BY 2 DESC
) A
LIMIT 1;