-- Solution 1: (779 ms, 0 B)

WITH INN AS
(
   SELECT DISTINCT ID 
   FROM TREE A
   WHERE ID NOT IN (SELECT DISTINCT P_ID FROM TREE B WHERE P_ID IS NOT NULL)
)

SELECT ID, CASE WHEN P_ID IS NULL THEN 'Root'
                WHEN ID IN (SELECT DISTINCT ID FROM INN) THEN 'Leaf'
                ELSE 'Inner' END AS TYPE
FROM TREE;
