-- Solution 1: (703 ms, 0 B)

SELECT PROJECT_ID, ROUND(AVG(EXPERIENCE_YEARS),2) AS AVERAGE_YEARS
FROM
(
    SELECT A.*, B.EXPERIENCE_YEARS
    FROM PROJECT A
    LEFT JOIN EMPLOYEE B
    ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
) A   
GROUP BY 1;
