-- Solution 1: (579 ms, 0 B)

WITH TEMP AS
(
    SELECT DISTINCT A.PRODUCT_ID
    FROM PRODUCT A
    LEFT JOIN SALES B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE SALE_DATE < '2019-01-01' OR SALE_DATE > '2019-03-31'
)


SELECT DISTINCT A.PRODUCT_ID, A.PRODUCT_NAME
FROM PRODUCT A
LEFT JOIN SALES B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE SALE_DATE >= '2019-01-01' AND SALE_DATE <= '2019-03-31' AND A.PRODUCT_ID NOT IN (SELECT DISTINCT PRODUCT_ID FROM TEMP);