-- Solution 1: (487 ms, 0 B)

SELECT EXTRA AS REPORT_REASON, COUNT(DISTINCT POST_ID) AS REPORT_COUNT
FROM ACTIONS
WHERE ACTION = 'report' AND ACTION_DATE = DATE_ADD('2019-07-05', INTERVAL -1 DAY)
GROUP BY 1;
