-- Solution 1: (546 ms, 0 B)

WITH USERS AS
(
   SELECT USER_ID, COUNT(DISTINCT SESSION_ID) AS SESH 
   FROM ACTIVITY 
   WHERE ACTIVITY_DATE > DATE_ADD('2019-07-27', INTERVAL -30 DAY) AND ACTIVITY_DATE <= '2019-07-27'
   #AND ACTIVITY_TYPE IS NOT NULL
   GROUP BY 1
)


SELECT IFNULL (
(
    SELECT ROUND(AVG(SESH),2) AS AVERAGE_SESSIONS_PER_USER
    FROM USERS A
)  , 0.00 ) AS AVERAGE_SESSIONS_PER_USER;