-- Solution 1: (603 ms, 0 B)

SELECT QUERY_NAME, ROUND(AVG(QUAL),2) AS QUALITY, 
       ROUND((COUNT(CASE WHEN FLAG = 1 THEN QUERY_NAME END)*100)/COUNT(QUERY_NAME),2) AS POOR_QUERY_PERCENTAGE
FROM 
(
    SELECT A.*, RATING/POSITION AS QUAL, CASE WHEN RATING < 3 THEN 1 ELSE 0 END AS FLAG
    FROM QUERIES A
) A   
GROUP BY 1;