-- Solution 1: (1327 ms, 0 B)

WITH POSTS AS
(
   SELECT DISTINCT SUB_ID 
   FROM SUBMISSIONS 
   WHERE PARENT_ID IS NULL
)

SELECT A.SUB_ID AS POST_ID, COUNT(DISTINCT B.SUB_ID) AS NUMBER_OF_COMMENTS
FROM POSTS A
LEFT JOIN SUBMISSIONS B
ON A.SUB_ID = B.PARENT_ID
GROUP BY 1;