-- Solution 1: (579 ms, 0 B)

SELECT PRODUCT_ID, ROUND(NUM/DEN,2) AS AVERAGE_PRICE
FROM
(
    SELECT PRODUCT_ID, SUM(NUM) AS NUM, SUM(UNITS) AS DEN
    FROM
    (
        SELECT PRODUCT_ID, UNITS, PRICE, UNITS*PRICE AS NUM
        FROM
        (
            SELECT A.*, CASE WHEN A.PURCHASE_DATE >= B.START_DATE AND A.PURCHASE_DATE <= B.END_DATE 
                             THEN PRICE END AS PRICE
            FROM UNITSSOLD A
            LEFT JOIN PRICES B
            ON A.PRODUCT_ID = B.PRODUCT_ID AND A.PURCHASE_DATE >= B.START_DATE AND A.PURCHASE_DATE <= B.END_DATE 
        ) A 
    ) A    
    GROUP BY 1
) A;  