-- Solution 1: (859 ms, 0 B)

WITH EXAMS AS
(
    SELECT STUDENT_ID, SUBJECT_NAME, COUNT(*) AS CNT
    FROM EXAMINATIONS
    GROUP BY 1,2
)    

SELECT A.*, CASE WHEN B.CNT IS NULL THEN 0 ELSE B.CNT END AS ATTENDED_EXAMS
FROM
(
    SELECT A.*, B.SUBJECT_NAME
    FROM STUDENTS A
    CROSS JOIN SUBJECTS B
) A  
LEFT JOIN EXAMS B
ON A.STUDENT_ID = B.STUDENT_ID AND A.SUBJECT_NAME = B.SUBJECT_NAME
ORDER BY STUDENT_ID, SUBJECT_NAME;