-- Solution 1: (544 ms, 0 B)

WITH AVG_WEATHER AS
(
  SELECT COUNTRY_ID, AVG(WEATHER_STATE) AS AVR
  FROM WEATHER
  WHERE DAY >= '2019-11-01' AND DAY <= '2019-11-30'
  GROUP BY 1
 
)

SELECT COUNTRY_NAME, CASE WHEN AVR <= 15 THEN 'Cold'
                          WHEN AVR >= 25 THEN 'Hot'
                          ELSE 'Warm' END AS WEATHER_TYPE
FROM
(
    SELECT A.*, B.AVR 
    FROM COUNTRIES A
    INNER JOIN AVG_WEATHER B
    ON A.COUNTRY_ID = B.COUNTRY_ID
) A;