-- Solution 1: (231 ms, 0 B)

WITH TEAM_SIZE AS 
(
   SELECT TEAM_ID, COUNT(DISTINCT EMPLOYEE_ID) AS TEAM_SIZE
   FROM EMPLOYEE
   GROUP BY 1
)

SELECT A.EMPLOYEE_ID, B.TEAM_SIZE
FROM EMPLOYEE A
LEFT JOIN TEAM_SIZE B
ON A.TEAM_ID = B.TEAM_ID;