-- Solution 1: (608 ms, 0 B)

WITH TEMP AS
(    
    SELECT AD_ID, CASE WHEN CTR IS NULL THEN 0.00 ELSE CTR END AS CTR
    FROM 
    (
        SELECT AD_ID, ROUND(CLICKED_COUNT*100/TOTAL_COUNT,2) AS CTR
        FROM
        (
            SELECT AD_ID, COUNT(CASE WHEN ACTION = 'Clicked' THEN USER_ID END) AS CLICKED_COUNT,
                          COUNT(USER_ID) AS TOTAL_COUNT
            FROM ADS
            WHERE ACTION NOT IN ('Ignored')
            GROUP BY 1
        ) A
    ) B   
)

SELECT DISTINCT A.AD_ID, CASE WHEN B.AD_ID IS NOT NULL THEN B.CTR ELSE 0.00 END AS CTR
FROM ADS A
LEFT JOIN TEMP B
ON A.AD_ID = B.AD_ID
ORDER BY 2 DESC, 1;