-- Solution 1: (490 ms, 0 B)

WITH ORDERS1 AS
(
   SELECT PRODUCT_ID, SUM(UNIT) AS UNITS
   FROM ORDERS
   WHERE ORDER_DATE >= '2020-02-01' AND ORDER_DATE <= '2020-02-29'
   GROUP BY 1
   HAVING UNITS >= 100
) 

SELECT DISTINCT A.PRODUCT_NAME, UNITS AS UNIT
FROM PRODUCTS A
INNER JOIN ORDERS1 B
ON A.PRODUCT_ID = B.PRODUCT_ID;
