-- Solution 1: (323 ms, 0 B)

WITH TEMP AS
(
    SELECT CASE WHEN MINUTES >= 0 AND MINUTES < 5 THEN '[0-5>' 
                WHEN MINUTES >= 5 AND MINUTES < 10 THEN '[5-10>'
                WHEN MINUTES >= 10 AND MINUTES < 15 THEN '[10-15>'
                WHEN MINUTES >= 15 THEN '15 or more' END AS BIN,
           COUNT(DISTINCT SESSION_ID) AS TOTAL
    FROM 
    (
       SELECT A.*, DURATION/60 AS MINUTES 
       FROM SESSIONS A
    ) A
    GROUP BY 1
),
TEMP1 AS
(
   SELECT '[0-5>' AS BIN
   UNION
   SELECT '[5-10>' AS BIN
   UNION
   SELECT '[10-15>' AS BIN
   UNION
   SELECT '15 or more' AS BIN
)

SELECT A.*, CASE WHEN B.TOTAL IS NULL THEN 0 ELSE B.TOTAL END AS TOTAL 
FROM TEMP1 A
LEFT JOIN TEMP B
ON A.BIN = B.BIN;