-- Solution 1: (1236 ms, 0 B)

WITH JUN_SALES AS
(
    SELECT CUSTOMER_ID, SUM(TOT_PRICE) AS TOT_PRICE
    FROM
    (
        SELECT CUSTOMER_ID, A.PRODUCT_ID, QUANTITY, PRICE, QUANTITY*PRICE AS TOT_PRICE
        FROM ORDERS A
        LEFT JOIN PRODUCT B
        ON A.PRODUCT_ID = B.PRODUCT_ID
        WHERE ORDER_DATE >= '2020-06-01' AND ORDER_DATE <= '2020-06-30'
    ) A
    GROUP BY 1
), JUL_SALES AS
(
    SELECT CUSTOMER_ID, SUM(TOT_PRICE) AS TOT_PRICE
    FROM
    (
        SELECT CUSTOMER_ID, A.PRODUCT_ID, QUANTITY, PRICE, QUANTITY*PRICE AS TOT_PRICE
        FROM ORDERS A
        LEFT JOIN PRODUCT B
        ON A.PRODUCT_ID = B.PRODUCT_ID
        WHERE ORDER_DATE >= '2020-07-01' AND ORDER_DATE <= '2020-07-31'
    ) A
    GROUP BY 1
)

SELECT DISTINCT CUSTOMER_ID, NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN 
(
   SELECT DISTINCT CUSTOMER_ID FROM JUN_SALES
   WHERE CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM JUL_SALES WHERE TOT_PRICE >= 100) AND TOT_PRICE >= 100
);