-- Solution 1: (587 ms,	0 B)

SELECT TRIM(LOWER(PRODUCT_NAME)) AS PRODUCT_NAME, 
CONCAT(EXTRACT(YEAR FROM SALE_DATE),'-',LPAD(EXTRACT(MONTH FROM SALE_DATE),2,0)) AS SALE_DATE, COUNT(DISTINCT SALE_ID) AS TOTAL
FROM SALES
GROUP BY 1,2
ORDER BY 1,2;