-- Solution 1: (626 ms, 0 B)

SELECT CONCAT(DATE_FORMAT(ORDER_DATE,'%Y'),'-',DATE_FORMAT(ORDER_DATE,'%m')) AS MONTH, COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM ORDERS
WHERE INVOICE > 20
GROUP BY 1;