-- Solution 1: (556 ms, 0 B)

SELECT NAME AS WAREHOUSE_NAME, SUM(VOLUME) AS VOLUME
FROM
(
    SELECT A.*, UNITS*WIDTH*LENGTH*HEIGHT AS VOLUME
    FROM
    (
        SELECT A.*, WIDTH, LENGTH, HEIGHT
        FROM WAREHOUSE A
        LEFT JOIN PRODUCTS B
        ON A.PRODUCT_ID = B.PRODUCT_ID
    ) A  
) A
GROUP BY 1;