-- Solution 1: (914 ms, 0 B)

SELECT CUSTOMER_ID, COUNT(*) AS COUNT_NO_TRANS
FROM
(
   SELECT VISIT_ID, CUSTOMER_ID
   FROM VISITS
   WHERE VISIT_ID NOT IN (SELECT DISTINCT VISIT_ID FROM TRANSACTIONS)
) A
GROUP BY 1;