-- Solution 1: (579 ms, 0 B)

SELECT NAME, BALANCE
FROM USERS A
LEFT JOIN
(
    SELECT ACCOUNT, SUM(AMOUNT) AS BALANCE
    FROM TRANSACTIONS
    GROUP BY 1
) B    
ON A.ACCOUNT = B.ACCOUNT
WHERE BALANCE > 10000;