-- Solution 1: (695 ms, 0 B)

SELECT DISTINCT SELLER_NAME
FROM SELLER
WHERE SELLER_ID NOT IN
(
    SELECT DISTINCT SELLER_ID 
    FROM ORDERS
    WHERE SALE_DATE >= '2020-01-01' AND SALE_DATE <= '2020-12-31'
)
ORDER BY 1;   

-- Solution 2: (847 ms, 0 B)
WITH TEMP AS
(
   SELECT DISTINCT SELLER_ID
   FROM ORDERS
   WHERE SALE_DATE >= '2020-01-01' AND SALE_DATE <= '2020-12-31'
) 

SELECT SELLER_NAME
FROM SELLER 
WHERE SELLER_ID NOT IN (SELECT * FROM TEMP)
ORDER BY 1;