-- Solution 1: (259 ms, 0 B)

SELECT MACHINE_ID, ROUND(AVG(PROCESS),3) AS PROCESSING_TIME
FROM
(
    SELECT A.MACHINE_ID, A.PROCESS_ID, B.TIMESTAMP - A.TIMESTAMP AS PROCESS
    FROM 
    (
        SELECT * FROM ACTIVITY
        WHERE ACTIVITY_TYPE = 'start'
    ) A
    LEFT JOIN
    (
        SELECT * FROM ACTIVITY
        WHERE ACTIVITY_TYPE = 'end'
    ) B
    ON A.MACHINE_ID = B.MACHINE_ID AND A.PROCESS_ID = B.PROCESS_ID
) A
GROUP BY 1;
                  