-- Solution 1: (676 ms, 0 B)

SELECT NAME, CASE WHEN REST IS NULL THEN 0 ELSE REST END AS REST,
             CASE WHEN PAID IS NULL THEN 0 ELSE PAID END AS PAID,
             CASE WHEN CANCELED IS NULL THEN 0 ELSE CANCELED END AS CANCELED,
             CASE WHEN REFUNDED IS NULL THEN 0 ELSE REFUNDED END AS REFUNDED
FROM
(
    SELECT A.NAME, SUM(REST) AS REST, SUM(PAID) AS PAID, SUM(CANCELED) AS CANCELED, SUM(REFUNDED) AS REFUNDED
    FROM PRODUCT A
    LEFT JOIN INVOICE B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY 1
    ORDER BY 1
) A;