-- Solution 1: (768 ms, 0 B)

WITH TEMP AS 
(
   SELECT DISTINCT PRODUCT_ID, 'store1' AS STORE, STORE1 AS PRICE
   FROM PRODUCTS
   UNION
   SELECT DISTINCT PRODUCT_ID, 'store2' AS STORE, STORE2 AS PRICE
   FROM PRODUCTS
   UNION
   SELECT DISTINCT PRODUCT_ID, 'store3' AS STORE, STORE3 AS PRICE
   FROM PRODUCTS
)

SELECT A.*  FROM TEMP A
WHERE PRICE IS NOT NULL;