-- Solution 1: (681 ms, 0 B)

WITH MANAGER_SALARY AS
(
   SELECT DISTINCT ID, SALARY
   FROM EMPLOYEE
   WHERE ID IN (SELECT DISTINCT MANAGERID FROM EMPLOYEE)
)

SELECT NAME AS EMPLOYEE
FROM
(
    SELECT A.ID, A.NAME, A.SALARY, A.MANAGERID, B.SALARY AS MANAGERSALARY, 
           A.SALARY - B.SALARY AS DIFF
    FROM EMPLOYEE A
    LEFT JOIN MANAGER_SALARY B
    ON A.MANAGERID = B.ID
) A
WHERE DIFF > 0;