-- Solution 1: (779 ms, 0 B)

WITH TEMP AS
(
   SELECT DISTINCT EMPLOYEE_ID FROM EMPLOYEES
   UNION
   SELECT DISTINCT EMPLOYEE_ID FROM SALARIES
)

SELECT * FROM TEMP
WHERE EMPLOYEE_ID NOT IN (SELECT DISTINCT EMPLOYEE_ID FROM EMPLOYEES)
OR EMPLOYEE_ID NOT IN (SELECT DISTINCT EMPLOYEE_ID FROM SALARIES)
ORDER BY 1;