-- Solution 1: (350 ms, 0 B)

SELECT DISTINCT B.ID 
FROM WEATHER A
LEFT JOIN WEATHER B
ON A.RECORDDATE = DATE_ADD(B.RECORDDATE, INTERVAL -1 DAY) AND A.TEMPERATURE < B.TEMPERATURE
WHERE B.ID IS NOT NULL;