-- Solution 1: (453 ms, 0 B)

SELECT PLAYER_ID, DEVICE_ID
FROM
(
    SELECT A.*, ROW_NUMBER() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS ROW_NUM
    FROM ACTIVITY A
) A 
WHERE ROW_NUM = 1;
