-- Solution 1: (724 ms, 0 B)

SELECT CUSTOMER_NUMBER
FROM
(
    SELECT CUSTOMER_NUMBER, COUNT(DISTINCT ORDER_NUMBER) AS ORDERS
    FROM ORDERS
    GROUP BY 1
    ORDER BY 2 DESC
) A   
LIMIT 1;