-- Solution 1: (555 ms, 0 B)

WITH SENT_REQUESTS AS
(
    
   SELECT COUNT(DISTINCT SENT) AS SENT 
   FROM
   (
       SELECT CONCAT(SENDER_ID,SEND_TO_ID) AS SENT
       FROM FRIENDREQUEST
   ) A    
),
ACCEPTED_REQUESTS AS
(

   SELECT COUNT(DISTINCT ACCEPTED) AS ACCEPTED 
   FROM
   (
       SELECT CONCAT(REQUESTER_ID, ACCEPTER_ID) AS ACCEPTED
       FROM REQUESTACCEPTED
   ) A    
)


SELECT CASE WHEN SENT = 0 THEN 0.00 ELSE ROUND(ACCEPTED/SENT,2) END AS ACCEPT_RATE
FROM SENT_REQUESTS A
CROSS JOIN ACCEPTED_REQUESTS B;