-- Solution 1: (301 ms,	0 B)

WITH TEMP AS
(
    SELECT * FROM CINEMA
    WHERE FREE = 1
)    

SELECT * FROM 
(
    SELECT DISTINCT A.SEAT_ID
    FROM TEMP A
    INNER JOIN TEMP B
    ON A.SEAT_ID = B.SEAT_ID - 1

    UNION

    SELECT DISTINCT A.SEAT_ID
    FROM TEMP A
    INNER JOIN TEMP B
    ON A.SEAT_ID = B.SEAT_ID + 1
) A
ORDER BY 1;