-- Solution 1: (1230 ms, 0 B)

WITH NAME AS 
(
    SELECT DISTINCT NAME FROM
    (
        SELECT A.SALES_ID, A.NAME, B.COM_ID, B.COM_NAME
        FROM SALESPERSON A
        LEFT JOIN 
        (
            SELECT B.ORDER_ID, B.SALES_ID, B.COM_ID, C.NAME AS COM_NAME
            FROM ORDERS B
            LEFT JOIN COMPANY C
            ON B.COM_ID = C.COM_ID
        ) B
        ON A.SALES_ID = B.SALES_ID
    ) A
    WHERE COM_NAME LIKE 'RED' 
)   

SELECT DISTINCT NAME FROM SALESPERSON
WHERE NAME NOT IN (SELECT * FROM NAME);