-- Solution 1: (244 ms, 0 B)

SELECT DISTINCT SHORTEST FROM
(
    SELECT A.X AS X1, B.X AS X2, ABS(A.X - B.X) AS SHORTEST
    FROM POINT A
    CROSS JOIN POINT B
) A    
WHERE SHORTEST != 0
ORDER BY SHORTEST 
LIMIT 1;